# Generated by Django 6.0.4 on 2026-04-17 14:41

import django.core.validators
import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='0123456789', help_text='Le numéro doit contenir exactement 10 chiffres (0355555555)', max_length=10, validators=[django.core.validators.RegexValidator(message='Le numéro doit contenir exactement 10 chiffres (0355555555)', regex='^0\\d{9}$')], verbose_name='Téléphone')),
                ('email', models.EmailField(default='contact@dev.com', max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Depannage PC', unique=True, verbose_name='Nom du site')),
                ('owner_name', models.CharField(default='Your name', unique=True, verbose_name='Nom de propriétaire')),
                ('primary_color', models.CharField(default='#000000', help_text='Format:#RRGGBB', validators=[django.core.validators.RegexValidator(message='Le format doit être #RRGGBB (ex: #FF5733)', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Couleur principale')),
            ],
            options={
                'verbose_name': 'Accueil',
                'verbose_name_plural': 'Accueil',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nom du service')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.IntegerField(blank=True, help_text='Ex : 10000', null=True, verbose_name='Prix')),
                ('icon', models.CharField(blank=True, help_text='Emoji ou classe CSS', max_length=50, verbose_name='Icône')),
                ('order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Nom')),
                ('link', models.URLField(default='', verbose_name='Lien')),
                ('icon', models.CharField(default='', help_text='Ex : logo-nom_du_site', verbose_name='icône')),
                ('is_active', models.BooleanField(default=True, verbose_name='est actif')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Réseau social',
                'verbose_name_plural': 'Réseaux sociaux',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(unique=True)),
                ('email', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('is_active', models.BooleanField(db_column='isActive')),
            ],
            options={
                'db_table': 'User',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Dépanneur', max_length=200, verbose_name='Titre')),
                ('content', models.TextField(default='Mon contenu', verbose_name='Contenu')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'Page A propos',
                'verbose_name_plural': 'Page A propos',
                'abstract': False,
            },
        ),
    ]
