# Generated by Django 6.0.4 on 2026-04-19 19:22

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_review'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.PositiveIntegerField(blank=True, help_text='Ex : 10000', null=True, verbose_name='Prix'),
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('price', models.PositiveIntegerField(verbose_name='Prix')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveIntegerField(verbose_name="Ordre d'affichage")),
                ('icon', models.CharField(blank=True, help_text='Emoji ou classe CSS', max_length=50, verbose_name='Icône')),
                ('warranty', models.CharField(blank=True, max_length=200, verbose_name='Garantie')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardware_image', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'Matériel',
                'verbose_name_plural': 'Matériels',
                'ordering': ['order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('price', models.PositiveIntegerField(verbose_name='Prix')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveIntegerField(verbose_name="Ordre d'affichage")),
                ('icon', models.CharField(blank=True, help_text='Emoji ou classe CSS', max_length=50, verbose_name='Icône')),
                ('version', models.CharField(blank=True, max_length=200, verbose_name='Version')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_image', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'Logiciel',
                'verbose_name_plural': 'Logiciels',
                'ordering': ['order', 'name'],
                'abstract': False,
            },
        ),
    ]
