# Generated by Django 6.0.4 on 2026-04-19 19:46

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_service_price_hardware_software'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(db_column='createdAt', db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
