# Generated by Django 6.0.4 on 2026-04-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
