# Generated by Django 6.0.4 on 2026-04-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hardware_image_url_software_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_active',
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
