from .home import Home
from .contact import Contact
from .about import About
from .social_network import SocialNetwork
from .user import User
from .service import Service
from .review import Review
from .hardware_product import Hardware
from .software_product import Software